# Generated by Django 3.0.1 on 2019-12-26 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultyuser',
            name='department_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='facultyuser',
            name='ldap_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.DateField(default=datetime.date(2020, 1, 2)),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
